[project]
name = "virtualdj-mcp-server"
version = "1.0.1"
description = "Control VirtualDJ software via a MCP server"
readme = "README.md"
authors = [
     { name = "DJCEL", email = "16272026+DJCEL@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
  "fastmcp"
  "httpx",
  "psutil",
  "rich",
]

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]